// Funcionários da Vailson Hair
export const funcionarios = [
  { 
    id: 1, 
    nome: 'Erica Brito', 
    especialidade: 'Cabelos', 
    telefone: '(11) 99999-1111', 
    email: 'erica@vailsonhair.com',
    dataContratacao: '2023-01-15',
    salarioBase: 1800.00,
    comissaoPercentual: 40,
    ativo: true,
    avatar: 'EB',
    cor: 'bg-purple-500',
  },
  { 
    id: 2, 
    nome: 'Chica', 
    especialidade: 'Manicure/Pedicure', 
    telefone: '(11) 99999-2222', 
    email: 'chica@vailsonhair.com',
    dataContratacao: '2023-03-10',
    salarioBase: 1800.00,
    comissaoPercentual: 35,
    ativo: true,
    avatar: 'CH',
    cor: 'bg-pink-500',
  },
  { 
    id: 3, 
    nome: 'Biel', 
    especialidade: 'Barbearia', 
    telefone: '(11) 99999-3333', 
    email: 'biel@vailsonhair.com',
    dataContratacao: '2023-06-20',
    salarioBase: 1800.00,
    comissaoPercentual: 40,
    ativo: true,
    avatar: 'BL',
    cor: 'bg-blue-500',
  },
  { 
    id: 4, 
    nome: 'Gabriela Saraiva', 
    especialidade: 'Estética Facial', 
    telefone: '(11) 99999-4444', 
    email: 'gabriela@vailsonhair.com',
    dataContratacao: '2023-09-05',
    salarioBase: 1800.00,
    comissaoPercentual: 35,
    ativo: true,
    avatar: 'GS',
    cor: 'bg-yellow-500',
  },
  { 
    id: 5, 
    nome: 'Jaline Teixeira', 
    especialidade: 'Cabelos/Coloração', 
    telefone: '(11) 99999-5555', 
    email: 'jaline@vailsonhair.com',
    dataContratacao: '2023-11-12',
    salarioBase: 1800.00,
    comissaoPercentual: 40,
    ativo: true,
    avatar: 'JT',
    cor: 'bg-green-500',
  },
  { 
    id: 6, 
    nome: 'Rafael Vicente', 
    especialidade: 'Barbearia/Cortes', 
    telefone: '(11) 99999-6666', 
    email: 'rafael@vailsonhair.com',
    dataContratacao: '2024-02-18',
    salarioBase: 1800.00,
    comissaoPercentual: 40,
    ativo: true,
    avatar: 'RV',
    cor: 'bg-indigo-500',
  },
  { 
    id: 7, 
    nome: 'Vailson', 
    especialidade: 'Proprietário/Master', 
    telefone: '(11) 99999-7777', 
    email: 'vailson@vailsonhair.com',
    dataContratacao: '2023-01-01',
    salarioBase: 5000.00,
    comissaoPercentual: 50,
    ativo: true,
    avatar: 'VH',
    cor: 'bg-red-500',
  },
];

// Profissionais (alias para funcionários - usado nos agendamentos)
export const profissionais = funcionarios;