// Serviços completos
export const servicos = [
  // Cabelo
  { id: 1, nome: 'Ação Promocional Erik Kened', categoria: 'Cabelo', duracao: 30, preco: 179.99, comissaoPadrao: 35 },
  { id: 2, nome: 'Ação Promocional Keune Day', categoria: 'Cabelo', duracao: 30, preco: 189.00, comissaoPadrao: 35 },
  { id: 3, nome: 'Alinhamento - Cabelos Curtos', categoria: 'Cabelo', duracao: 150, preco: 250.00, comissaoPadrao: 35, descricao: 'Alinhamento dos fios. Cabelos com comprimento até a base do pescoço.' },
  { id: 4, nome: 'Alinhamento - Cabelos Extra Longos', categoria: 'Cabelo', duracao: 90, preco: 350.00, comissaoPadrao: 35, descricao: 'Alinhamento dos Fios. Cabelos com comprimento igual ou que ultrapasse a linha dos cotovelos.' },
  { id: 5, nome: 'Alinhamento - Cabelos Longos', categoria: 'Cabelo', duracao: 90, preco: 300.00, comissaoPadrao: 35, descricao: 'Alinhamento dos fios. Cabelos com comprimento que ultrapassa a linha das axilas.' },
  { id: 6, nome: 'Alinhamento - Cabelos Médios', categoria: 'Cabelo', duracao: 150, preco: 280.00, comissaoPadrao: 35, descricao: 'Alinhamento dos Fios. Fios com comprimento até a linha da axila.' },
  { id: 7, nome: 'Alinhamento Capilar - Masculino', categoria: 'Barbearia', duracao: 60, preco: 90.00, comissaoPadrao: 35 },
  { id: 8, nome: 'Almoço', categoria: 'Outros', duracao: 30, preco: 39.90, comissaoPadrao: 0 },
  { id: 9, nome: 'Alongamento de Cílios Fio a Fio', categoria: 'Estética Facial', duracao: 120, preco: 250.00, comissaoPadrao: 40, descricao: 'O alongamento de cílios é um método que permite alongar e valorizar a maquiagem e a expressão do olhar.' },
  { id: 10, nome: 'Alongamento de Cílios Tela', categoria: 'Estética Facial', duracao: 30, preco: 200.00, comissaoPadrao: 40, precoVariavel: true, descricao: 'A partir de R$ 200,00' },
  { id: 11, nome: 'Alongamento de Unha - Fibra de Vidro', categoria: 'Manicure e Pedicure', duracao: 180, preco: 190.00, comissaoPadrao: 30, descricao: 'Técnica de alongamento feito a partir de fios de fibra de vidro fixadas na unha.' },
  { id: 12, nome: 'Aplicação Cílios', categoria: 'Estética Facial', duracao: 30, preco: 40.00, comissaoPadrao: 40 },
  { id: 13, nome: 'Aplicação de Tintura', categoria: 'Cabelo', duracao: 30, preco: 80.00, comissaoPadrao: 45, precoVariavel: true, descricao: 'Aplicação de tintura com o produto trazido pelo cliente. A partir de R$ 80,00' },
  { id: 14, nome: 'Aplicação produto cliente', categoria: 'Cabelo', duracao: 30, preco: 35.00, comissaoPadrao: 35 },
  { id: 15, nome: 'Axilas', categoria: 'Depilação', duracao: 30, preco: 20.00, comissaoPadrao: 30, descricao: 'Depilação com cera na região das axilas.' },
  { id: 16, nome: 'BabyLiss', categoria: 'Cabelo', duracao: 60, preco: 40.00, comissaoPadrao: 30, descricao: 'Modelação do cabelo criando cachos e/ou ondas.' },
  { id: 17, nome: 'Banho de Cálcio', categoria: 'Manicure e Pedicure', duracao: 60, preco: 80.00, comissaoPadrao: 30 },
  { id: 18, nome: 'Banho de Gel', categoria: 'Manicure e Pedicure', duracao: 60, preco: 100.00, comissaoPadrao: 30 },
  { id: 19, nome: 'Banho de lua', categoria: 'Estética Corporal', duracao: 30, preco: 140.00, comissaoPadrao: 35, descricao: 'O banho é realizado em quatro etapas que englobam a descoloração dos pêlos, esfoliação, nutrição e hidratação.' },
  { id: 20, nome: 'Barba completa', categoria: 'Barbearia', duracao: 30, preco: 50.00, comissaoPadrao: 35, descricao: 'Barba completa' },
  { id: 21, nome: 'Barboterapia', categoria: 'Barbearia', duracao: 30, preco: 55.00, comissaoPadrao: 35, descricao: 'É um procedimento que tem como objetivo promover o relaxamento.' },
  { id: 22, nome: 'Blindagem das Unhas', categoria: 'Manicure e Pedicure', duracao: 30, preco: 35.00, comissaoPadrao: 30, descricao: 'Consiste na aplicação de uma camada de gel ou acrílico na superfície da unha.' },
  { id: 23, nome: 'Botox Capilar', categoria: 'Cabelo', duracao: 90, preco: 250.00, comissaoPadrao: 40, precoVariavel: true, descricao: 'É um tratamento estético que tira o frizz e reduz o volume dos cabelos. A partir de R$ 250,00' },
  { id: 24, nome: 'Braços', categoria: 'Depilação', duracao: 30, preco: 35.00, comissaoPadrao: 30, descricao: 'Depilação com cera na região dos braços.' },
  { id: 25, nome: 'Buço', categoria: 'Depilação', duracao: 30, preco: 25.00, comissaoPadrao: 30, descricao: 'Depilação com cera na região do buço.' },
  { id: 26, nome: 'Buço com Linha', categoria: 'Depilação', duracao: 30, preco: 25.00, comissaoPadrao: 30, precoVariavel: true, descricao: 'Depilação do buço com linha. A partir de R$ 25,00' },
  { id: 27, nome: 'Café da Manhã', categoria: 'Outros', duracao: 30, preco: 250.00, comissaoPadrao: 0 },
  { id: 28, nome: 'Cauterização Capilar', categoria: 'Cabelo', duracao: 60, preco: 180.00, comissaoPadrao: 40, precoVariavel: true, descricao: 'A cauterização capilar é um tipo de tratamento para os cabelos danificados. A partir de R$ 180,00' },
  { id: 29, nome: 'Chapinha', categoria: 'Cabelo', duracao: 30, preco: 20.00, comissaoPadrao: 30, descricao: 'Somente pranchar os cabelos.' },
  { id: 30, nome: 'Coloração Tonalização até 1,5cm', categoria: 'Cabelo', duracao: 30, preco: 130.00, comissaoPadrao: 45, descricao: 'Tintura dos cabelos com produtos do salão de beleza.' },
  { id: 31, nome: 'Coloração Tonalização até 3,0 cm', categoria: 'Cabelo', duracao: 30, preco: 160.00, comissaoPadrao: 45, descricao: 'Tintura dos cabelos com produtos do salão de beleza.' },
  { id: 32, nome: 'Coloração Tonalização até 5,0 cm', categoria: 'Cabelo', duracao: 30, preco: 180.00, comissaoPadrao: 45, descricao: 'Tintura dos cabelos com produtos do salão de beleza.' },
  { id: 33, nome: 'Coloração Tonalização completa dos fios', categoria: 'Cabelo', duracao: 30, preco: 280.00, comissaoPadrao: 45, descricao: 'Tintura dos cabelos com produtos do salão de beleza.' },
  { id: 34, nome: 'Contorno', categoria: 'Depilação', duracao: 60, preco: 60.00, comissaoPadrao: 30, descricao: 'Depilação com cera na região da virilha.' },
  { id: 35, nome: 'Corte Franja', categoria: 'Cabelo', duracao: 30, preco: 50.00, comissaoPadrao: 35, descricao: 'Incluídas lavagem e secagem' },
  { id: 36, nome: 'Corte Masculino', categoria: 'Barbearia', duracao: 30, preco: 60.00, comissaoPadrao: 35, descricao: 'Incluídas lavagem e secagem' },
  { id: 37, nome: 'Corte Unha', categoria: 'Manicure e Pedicure', duracao: 30, preco: 15.00, comissaoPadrao: 30 },
  { id: 38, nome: 'Decoração de Unhas', categoria: 'Manicure e Pedicure', duracao: 30, preco: 0, comissaoPadrao: 30, precoVariavel: true, descricao: 'Sob consulta' },
  { id: 39, nome: 'DEPILAÇÃO COMPLETA - PROMOÇÃO', categoria: 'Depilação', duracao: 30, preco: 150.00, comissaoPadrao: 30, descricao: 'PERNA INTEIRA + CONTORNO COMPLETO + AXILAS OU BUÇO.' },
  { id: 40, nome: 'Design de Corte Feminino', categoria: 'Cabelo', duracao: 30, preco: 160.00, comissaoPadrao: 40, descricao: 'O corte de cabelo retira as pontas ressecadas do cabelo e ajuda no crescimento dos fios.' },
  { id: 41, nome: 'Design de Mechas', categoria: 'Cabelo', duracao: 180, preco: 350.00, comissaoPadrao: 45, precoVariavel: true, descricao: 'A partir de R$ 350,00' },
  { id: 42, nome: 'Design de Sobrancelha', categoria: 'Estética Facial', duracao: 30, preco: 60.00, comissaoPadrao: 40 },
  { id: 43, nome: 'Design de Sobrancelha e Buço', categoria: 'Sobrancelha', duracao: 30, preco: 80.00, comissaoPadrao: 40, precoVariavel: true, descricao: 'A partir de R$ 80,00' },
  { id: 44, nome: 'Design de Sobrancelha Henna', categoria: 'Sobrancelha', duracao: 30, preco: 70.00, comissaoPadrao: 40, descricao: 'Técnica que busca alinhar os pelos da sobrancelha.' },
  { id: 45, nome: 'Despeguimentação', categoria: 'Estética Facial', duracao: 30, preco: 100.00, comissaoPadrao: 35 },
  { id: 46, nome: 'Escova - Cabelos Curtos', categoria: 'Cabelo', duracao: 30, preco: 50.00, comissaoPadrao: 30, descricao: 'Cabelos com comprimento até a base do pescoço.' },
  { id: 47, nome: 'Escova - Cabelos Extra Longos', categoria: 'Cabelo', duracao: 60, preco: 80.00, comissaoPadrao: 30, descricao: 'Cabelos com comprimento igual ou que ultrapasse a linha dos cotovelos.' },
  { id: 48, nome: 'Escova - Cabelos Longos', categoria: 'Cabelo', duracao: 60, preco: 70.00, comissaoPadrao: 30, descricao: 'Cabelos com comprimento que ultrapassa a linha das axilas.' },
  { id: 49, nome: 'Escova - Cabelos Médios', categoria: 'Cabelo', duracao: 30, preco: 60.00, comissaoPadrao: 30, descricao: 'Fios com comprimento até a linha da axila.' },
  { id: 50, nome: 'Esmaltação', categoria: 'Manicure e Pedicure', duracao: 30, preco: 20.00, comissaoPadrao: 25, descricao: 'Apenas passar ou trocar o esmalte das unhas das mãos.' },
  { id: 51, nome: 'Esmaltação em Gel', categoria: 'Manicure e Pedicure', duracao: 60, preco: 40.00, comissaoPadrao: 30 },
  { id: 52, nome: 'Fibra de Vidro - Manutenção', categoria: 'Manicure e Pedicure', duracao: 120, preco: 150.00, comissaoPadrao: 30, descricao: 'Técnica de alongamento feito a partir de fios de fibra de vidro.' },
  { id: 53, nome: 'Fitagem', categoria: 'Cabelo', duracao: 30, preco: 45.00, comissaoPadrao: 30 },
  { id: 54, nome: 'Francesinha', categoria: 'Manicure e Pedicure', duracao: 30, preco: 4.00, comissaoPadrao: 25 },
  { id: 55, nome: 'Hidratação', categoria: 'Cabelo', duracao: 30, preco: 90.00, comissaoPadrao: 35, precoVariavel: true, descricao: 'Utilizada para repor a umidade natural, nutrientes e queratina perdida. A partir de R$ 90,00' },
  { id: 56, nome: 'Hidratação - Day by day com Escova', categoria: 'Cabelo', duracao: 30, preco: 90.00, comissaoPadrao: 35, descricao: 'Utilizada para repor a umidade natural, nutrientes e queratina perdida. ESCOVA DE BRINDE!!' },
  { id: 57, nome: 'Hidratação Keune com Escova', categoria: 'Cabelo', duracao: 30, preco: 129.00, comissaoPadrao: 35, descricao: 'Hidratação Keune + Escova de brinde.' },
  { id: 58, nome: 'Hidratação Premium - Erik Kened', categoria: 'Cabelo', duracao: 30, preco: 149.90, comissaoPadrao: 35, descricao: 'Nosso queridinho, tratamento capilar! Hidrata, Nutre e Reconstrói.' },
  { id: 59, nome: 'Lavagem Especial', categoria: 'Cabelo', duracao: 30, preco: 25.00, comissaoPadrao: 30, descricao: 'Aplicação de shampoo e condicionador para limpeza dos fios.' },
  { id: 60, nome: 'Limpeza de Pele', categoria: 'Estética Facial', duracao: 60, preco: 130.00, comissaoPadrao: 35, descricao: 'Higieniza, esfolia e remove células mortas.' },
  { id: 61, nome: 'Make Casual', categoria: 'Maquiagem', duracao: 30, preco: 120.00, comissaoPadrao: 35 },
  { id: 62, nome: 'Make Vip', categoria: 'Maquiagem', duracao: 30, preco: 140.00, comissaoPadrao: 35 },
  { id: 63, nome: 'Manutenção de Tela', categoria: 'Cabelo', duracao: 30, preco: 250.00, comissaoPadrao: 35 },
  { id: 64, nome: 'Manutenção em fita', categoria: 'Cabelo', duracao: 30, preco: 250.00, comissaoPadrao: 35 },
  { id: 65, nome: 'Mão', categoria: 'Manicure e Pedicure', duracao: 30, preco: 30.00, comissaoPadrao: 30, descricao: 'Cutilação e esmaltação das unhas das mãos.' },
  { id: 66, nome: 'Mão Promocional', categoria: 'Manicure e Pedicure', duracao: 30, preco: 22.00, comissaoPadrao: 30, descricao: 'VÁLIDO SOMENTE DE SEGUNDA À QUARTA.' },
  { id: 67, nome: 'Maquiagem', categoria: 'Maquiagem', duracao: 60, preco: 180.00, comissaoPadrao: 35, descricao: 'A maquiagem faz parte do dia a dia de muitas mulheres.' },
  { id: 68, nome: 'Maquiagem Sem Cílios', categoria: 'Maquiagem', duracao: 30, preco: 140.00, comissaoPadrao: 35, descricao: 'Maquiagem sem colocação de cílios postiços.' },
  { id: 69, nome: 'Massagem Relaxante', categoria: 'Estética Corporal', duracao: 60, preco: 0, comissaoPadrao: 35, precoVariavel: true, descricao: 'Sob consulta' },
  { id: 70, nome: 'Matização', categoria: 'Cabelo', duracao: 30, preco: 100.00, comissaoPadrao: 40, descricao: 'O procedimento serve para neutralizar reflexos indesejados.' },
  { id: 71, nome: 'Meia Perna', categoria: 'Depilação', duracao: 30, preco: 45.00, comissaoPadrao: 30, descricao: 'Depilação com cera na região de meia-perna' },
  { id: 72, nome: 'Micropigmentação Fio a Fio', categoria: 'Estética Facial', duracao: 120, preco: 0, comissaoPadrao: 40, precoVariavel: true, descricao: 'Sob consulta' },
  { id: 73, nome: 'Nutrição', categoria: 'Cabelo', duracao: 30, preco: 80.00, comissaoPadrao: 35, precoVariavel: true, descricao: 'A partir de R$ 80,00' },
  { id: 74, nome: 'Pé', categoria: 'Manicure e Pedicure', duracao: 30, preco: 30.00, comissaoPadrao: 30, descricao: 'Cutilação e esmaltação das unhas dos pés.' },
  { id: 75, nome: 'Pé Promocional', categoria: 'Manicure e Pedicure', duracao: 30, preco: 23.00, comissaoPadrao: 30, descricao: 'VÁLIDO SOMENTE DE SEGUNDA À QUARTA.' },
  { id: 76, nome: 'Penteado', categoria: 'Cabelo', duracao: 60, preco: 150.00, comissaoPadrao: 35, descricao: 'Penteado é o estilo ou arranjo dado aos cabelos.' },
  { id: 77, nome: 'Penteado Express', categoria: 'Cabelo', duracao: 30, preco: 130.00, comissaoPadrao: 35, descricao: 'Penteado menos elaborado e de execução mais rápida.' },
  { id: 78, nome: 'Perna inteira', categoria: 'Depilação', duracao: 60, preco: 90.00, comissaoPadrao: 30, descricao: 'Depilação com cera na região da perna inteira.' },
  { id: 79, nome: 'Preenchimento Labial', categoria: 'Estética Facial', duracao: 120, preco: 0, comissaoPadrao: 40, precoVariavel: true, descricao: 'Sob consulta' },
  { id: 80, nome: 'Reconstrução Capilar', categoria: 'Cabelo', duracao: 30, preco: 110.00, comissaoPadrao: 35, precoVariavel: true, descricao: 'Reconstrução dos cabelos, recuperando o seu brilho e força natural. A partir de R$ 110,00' },
  { id: 81, nome: 'Remoção Cílios', categoria: 'Estética Facial', duracao: 30, preco: 30.00, comissaoPadrao: 30 },
  { id: 82, nome: 'Remoção Top Colt', categoria: 'Manicure e Pedicure', duracao: 30, preco: 15.00, comissaoPadrao: 30 },
  { id: 83, nome: 'Remoção unha fibra', categoria: 'Manicure e Pedicure', duracao: 120, preco: 60.00, comissaoPadrao: 30, precoVariavel: true, descricao: 'A partir de R$ 60,00' },
  { id: 84, nome: 'Remoção Unha Gel', categoria: 'Manicure e Pedicure', duracao: 30, preco: 60.00, comissaoPadrao: 30 },
  { id: 85, nome: 'Retirar Blindagem', categoria: 'Manicure e Pedicure', duracao: 30, preco: 25.00, comissaoPadrao: 30 },
  { id: 86, nome: 'Retirara Mega', categoria: 'Cabelo', duracao: 60, preco: 150.00, comissaoPadrao: 35 },
  { id: 87, nome: 'Secagem', categoria: 'Cabelo', duracao: 30, preco: 45.00, comissaoPadrao: 30, descricao: 'Somente secar os cabelos.' },
  { id: 88, nome: 'Spa para os Pés', categoria: 'Manicure e Pedicure', duracao: 60, preco: 40.00, comissaoPadrao: 30 },
  { id: 89, nome: 'SPA para os Pés - Profundo', categoria: 'Manicure e Pedicure', duracao: 60, preco: 60.00, comissaoPadrao: 30 },
  { id: 90, nome: 'Taxa de Deslocamento', categoria: 'Outros', duracao: 30, preco: 0, comissaoPadrao: 0 },
  { id: 91, nome: 'Top Colt', categoria: 'Manicure e Pedicure', duracao: 30, preco: 25.00, comissaoPadrao: 30, precoVariavel: true, descricao: 'A partir de R$ 25,00' },
  { id: 92, nome: 'Trança', categoria: 'Cabelo', duracao: 30, preco: 70.00, comissaoPadrao: 35 },
  { id: 93, nome: 'Unha Postiça', categoria: 'Manicure e Pedicure', duracao: 30, preco: 60.00, comissaoPadrao: 30 },
  { id: 94, nome: 'Unha postiça cliente', categoria: 'Manicure e Pedicure', duracao: 30, preco: 35.00, comissaoPadrao: 30 },
];